intro: >
    "Robo Reflections" is a space where Faculty, Postdocs, and PhD students in Human-Robot Interaction (HRI) at the University of Michigan share reflections about the field. 
    We draw upon state-of-the-art as well as foundational work in HRI to engage engage in research critiques that potentiate transformations in HRI. 
    Our reflections cover the multiple areas of HRI, including algorithmic, systems, design, studies, and theories. 
    Our sources include the conferences of HRI, RSS, ICRA, IROS, CoRL, DIS, TEI, CHI, as well as related Journals. 
format: >
    We follow a reflection & critique style, led by one presenter each week.
    Participants are expected to volunteer to facilitate reflections by signing up in [this document](https://docs.google.com/spreadsheets/d/1PF5PssAB_XmaE2R_Q2ifxLI4gwcvai9Jnrg7xZ_pR-s/edit?usp=sharing). 
    The lead presenter will introduce the research piece and guide the reflections with prepared questions. 
    The other participants are not expected to have read the paper before coming, but they can do so if they wish.